### ISSUE TITLE
ERROR:  fincore(24, 0, 1073741824, 0x7fa812608010): Function not implemented

### ISSUE THREAD

**Issue by strk** [klando/pgfincore#4]
I just tried to use pgfincore on a PostgreSQL 9.3.6.
Got sources from git.postgresql.org, built and installed, CREATE EXTENSION worked, but then:

```
rt=# select * from pgfincore('rtlidar_dim_main');
DEBUG:  pgfincore: init done for base/16107634/33277925, in fork main
CONTEXT:  SQL function "pgfincore" statement 1
DEBUG:  pgfincore: about to work with base/16107634/33277925
CONTEXT:  SQL function "pgfincore" statement 1
ERROR:  fincore(24, 0, 1073741824, 0x7fa812608010): Function not implemented

CONTEXT:  SQL function "pgfincore" statement 1
```

Ideas ?

**Comment by strk** [comment]
This is on
Linux cdb 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by strk** [comment]
Thanks to @anarazel I solved this by undefining HAVE_FINCORE in fincore.h -- it would be nice to get this figured by a configure script of some sort...

**Comment by klando** [comment]
HEAD is a WIP for a patched linux with fincore support. I should clean that part ....
Note that stable releases of fincore are tagged.

**Comment by strk** [comment]
Thanks !
1.1.2 tag works out of the box.
