### ISSUE TITLE
mincore() changes significantly in upcoming 5.0 kernel

### ISSUE THREAD

**Issue by psoo** [klando/pgfincore#5]
Kernel 5.0 will change the semantics of mincore() in a way which has its consequences for at least the pgfincore() output. 

According to https://github.com/torvalds/linux/commit/574823bfab82d9d8fa47f422778043fbb4b4f50e, pgfincore() isn't able to report the number of pages (pages_mem and group_mem) in the pagecache anymore, since that information is restricted starting with this commit.

**Comment by psoo** [comment]
Kernel 5.0rc4 has reverted that change to mincore()[1], since this was indeed considered a regression.

Seems there's an ongoing discussion on how to change/make mincore() safer without changing
it significantly.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=30bac164aca750892b93eef350439a0562a68647

**Comment by klando** [comment]
Thank you for the follow up on this topic. Glad to see it has been reverted.
