### ISSUE TITLE
PostgreSQL 16 support

### ISSUE THREAD

**Issue by devrimgunduz** [klando/pgfincore#9]
Hi,,

Latest release fails to build against v16 (see below), and v16 is due next week. Can you please take a look?

Thanks

Regards, Devrim

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgfincore.bc pgfincore.c
In file included from /usr/pgsql-16/include/server/utils/relcache.h:18,
                 from /usr/pgsql-16/include/server/access/relation.h:19,
                 from /usr/pgsql-16/include/server/access/heapam.h:17,
                 from pgfincore.c:20:
pgfincore.c: In function 'pgfadvise':
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:26: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                          ^~~~~~~~
pgfincore.c:418:38: note: in expansion of macro 'relpathpg'
  418 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:44: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                            ^~~~~~~~
pgfincore.c:418:38: note: in expansion of macro 'relpathpg'
  418 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:63: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                                               ^~~~~~~~
pgfincore.c:418:38: note: in expansion of macro 'relpathpg'
  418 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
pgfincore.c: In function 'pgfadvise_loader':
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:26: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                          ^~~~~~~~
pgfincore.c:692:24: note: in expansion of macro 'relpathpg'
  692 |         relationpath = relpathpg(rel, forkName);
      |                        ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:44: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                            ^~~~~~~~
pgfincore.c:692:24: note: in expansion of macro 'relpathpg'
  692 |         relationpath = relpathpg(rel, forkName);
      |                        ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:63: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                                               ^~~~~~~~
pgfincore.c:692:24: note: in expansion of macro 'relpathpg'
  692 |         relationpath = relpathpg(rel, forkName);
      |                        ^~~~~~~~~
pgfincore.c: In function 'pgfincore':
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:26: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                          ^~~~~~~~
pgfincore.c:1001:38: note: in expansion of macro 'relpathpg'
 1001 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:44: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                            ^~~~~~~~
pgfincore.c:1001:38: note: in expansion of macro 'relpathpg'
 1001 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
pgfincore.c:206:31: error: 'struct RelationData' has no member named 'rd_node'; did you mean 'rd_id'?
  206 |         relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
      |                               ^~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:63: note: in definition of macro 'relpathbackend'
   86 |         GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
      |                                                               ^~~~~~~~
pgfincore.c:1001:38: note: in expansion of macro 'relpathpg'
 1001 |                 fctx->relationpath = relpathpg(fctx->rel, forkName);
      |                                      ^~~~~~~~~
make[1]: *** [<builtin>: pgfincore.o] Error 1
make[1]: *** Waiting for unfinished jobs....
pgfincore.c:418:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:19: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                         ^~~~~~~~
pgfincore.c:418:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:37: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                           ^~~~~~~~
pgfincore.c:418:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:56: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                                              ^~~~~~~~
pgfincore.c:692:17: error: no member named 'rd_node' in 'struct RelationData'
        relationpath = relpathpg(rel, forkName);
                       ^~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:19: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                         ^~~~~~~~
pgfincore.c:692:17: error: no member named 'rd_node' in 'struct RelationData'
        relationpath = relpathpg(rel, forkName);
                       ^~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:37: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                           ^~~~~~~~
pgfincore.c:692:17: error: no member named 'rd_node' in 'struct RelationData'
        relationpath = relpathpg(rel, forkName);
                       ^~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:56: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                                              ^~~~~~~~
pgfincore.c:1001:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:19: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                         ^~~~~~~~
pgfincore.c:1001:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:37: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                           ^~~~~~~~
pgfincore.c:1001:24: error: no member named 'rd_node' in 'struct RelationData'
                fctx->relationpath = relpathpg(fctx->rel, forkName);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pgfincore.c:206:31: note: expanded from macro 'relpathpg'
        relpathbackend((rel)->rd_node, (rel)->rd_backend, (forkname_to_number(text_to_cstring(forkName))))
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/common/relpath.h:86:56: note: expanded from macro 'relpathbackend'
        GetRelationPath((rlocator).dbOid, (rlocator).spcOid, (rlocator).relNumber, \
                                                              ^~~~~~~~

**Comment by devrimgunduz** [comment]
ping

**Comment by klando** [comment]
No notification from github, sorry for the delay. Will address shortly!

Thank you for the report btw.

**Comment by pgfincore** [comment]
@devrimgunduz It's fixed now on master, I'll update wiki on postgresql when it's tagged.
I've also officially dropped support for oldish versions and updated GHA accordingly.

**Comment by devrimgunduz** [comment]
Hi @pgfincore ,

You can also update here, as I get notifications from here.

Regards, Devrim

**Comment by klando** [comment]
hold I believe it's a missing a file.

**Comment by df7cb** [comment]
Thanks :)
